class CreateHouses < ActiveRecord::Migration[7.0]
  def change
    create_table :houses do |t|
      t.string :address
      t.integer :lotSizeAcres
      t.integer :lotSizeSquareFeet
      t.integer :associationFee
      t.integer :listPrice
      t.integer :bathroomsTotal
      t.integer :bedroomsTotal
      t.integer :mainLevelBathrooms
      t.integer :fireplacesTotal
      t.string :fireplaceFeature
      t.integer :garageSpaces
      t.integer :bathroomHalf
      t.integer :storiesTotal
      t.text :publicRemarks
      t.integer :livingArea
      t.integer :yearBuilt
      t.text :yearBuiltDetails
      t.string :standardStatus
      t.string :propertyType
      t.string :propertySubType
      t.date :listingContractDate
      t.integer :previousListPrice
      t.integer :originalListPrice
      t.string :contingency
      t.integer :numberOfUnitsTotal
      t.string :listingTerms
      t.integer :daysOnMarket
      t.string :appliances
      t.integer :roomsTotal
      t.string :exteriorFeatures
      t.string :flooring
      t.string :foundationDetails
      t.string :frontageType
      t.string :gas
      t.string :accessibilityFeatures
      t.string :heating
      t.string :occupantType
      t.string :roadSurfaceType
      t.string :roof
      t.string :constructionMaterials
      t.string :sewer
      t.integer :carportSpaces
      t.boolean :openParkingYN
      t.string :laundryFeatures
      t.text :privateRemarks
      t.integer :taxAssessedValue
      t.integer :taxAnnualAount
      t.string :taxYear
      t.string :subdivisionName
      t.string :buyerFinancing
      t.boolean :homeWarrantyYN
      t.string :architecturalStyle
      t.string :comunityFeatures
      t.string :patioAndPorchFeatures
      t.string :otherStructures
      t.boolean :attachedGarage
      t.boolean :carportYN
      t.date :contigentDate
      t.boolean :associationYN
      t.string :associationName
      t.string :associationFeeFrequency
      t.text :associationFeeIncludes
      t.string :photo
      t.string :showingContactPhone
      t.string :showingContactName
      t.text :exclusions
      t.text :inclusions
      t.string :elementarySchool
      t.string :elementarySchoolDistrict
      t.string :middleOrJuniorSchool
      t.string :middleOrJuniorSchoolDistrict
      t.string :highSchool
      t.string :highSchoolDistrict
      t.boolean :garageYN
      t.string :levels
      t.string :builderName
      t.string :builderModel
      t.text :interiorFeatures
      t.text :greenEnergyEfficient
      t.integer :walkScore
      t.integer :user_id
      
      t.timestamps
    end
  end
end
